import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Boxes, ClipboardPlus, PackageCheck, Plus, RefreshCw, Warehouse } from 'lucide-react'
import { createInventoryItem, createInventoryLot, createInventoryMovement, getInventoryOverview, getPlantOverview } from './api'
import type { InventoryOverview, PlantOverview } from './types'

const categories:Record<string,string>={RAW_MATERIAL:'Materia prima',PACKAGING_MATERIAL:'Material de empaque',OPERATING_SUPPLY:'Insumo operativo',WORK_IN_PROGRESS:'Producto en proceso',FINISHED_GOOD:'Producto terminado',SPARE_PART:'Repuesto'}
const quality:Record<string,string>={QUARANTINE:'Cuarentena',APPROVED:'Aprobado',REJECTED:'Rechazado',BLOCKED:'Bloqueado'}
const emptyItem={code:'',name:'',category:'RAW_MATERIAL',baseUnit:'KG',trackLots:true,minimumStock:0,notes:''}

export default function InventoryPage(){
 const [data,setData]=useState<InventoryOverview|null>(null),[plant,setPlant]=useState<PlantOverview|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState<'item'|'lot'|'movement'|null>(null),[busy,setBusy]=useState(false)
 const [item,setItem]=useState(emptyItem),[lot,setLot]=useState({itemId:'',internalCode:'',supplierLot:'',expiryDate:'',qualityStatus:'QUARANTINE',notes:''}),[move,setMove]=useState({itemId:'',lotId:'',warehouseId:'',locationId:'',movementType:'RECEIPT',quantity:0,reference:'',notes:''})
 const load=async()=>{setError('');try{const [i,p]=await Promise.all([getInventoryOverview(),getPlantOverview()]);setData(i);setPlant(p)}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar inventarios')}}
 useEffect(()=>{let active=true;Promise.all([getInventoryOverview(),getPlantOverview()]).then(([i,p])=>{if(active){setData(i);setPlant(p)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'No fue posible cargar inventarios')});return()=>{active=false}},[])
 const selectedItem=data?.items.find(i=>i.id===move.itemId); const selectedWarehouse=plant?.warehouses.find(w=>w.id===move.warehouseId)
 const total=useMemo(()=>data?.balances.reduce((s,b)=>s+b.quantity,0)??0,[data])
 const run=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');try{await action();setDialog(null);setNotice(message);await load()}catch(e){setError(e instanceof Error?e.message:'No fue posible guardar')}finally{setBusy(false)}}
 if(!data||!plant)return <main><div className="loading"><RefreshCw className="spin"/>Cargando inventarios…</div></main>
 return <main><header><div><span className="eyebrow">TRAZABILIDAD DE MATERIALES</span><h1>Inventarios</h1><p>Artículos, lotes y existencias por bodega y ubicación.</p></div><button className="refresh" onClick={()=>void load()}><RefreshCw size={15}/>Actualizar</button></header>
 {error&&<div className="message error">{error}</div>}{notice&&<div className="message success">{notice}</div>}
 <section className="inventory-metrics"><div><Boxes/><span>Artículos activos</span><b>{data.items.length}</b></div><div><Warehouse/><span>Existencia registrada</span><b>{total.toLocaleString('es-CO')}</b></div><div><AlertTriangle/><span>Bajo mínimo</span><b>{data.lowStockItems}</b></div><div><PackageCheck/><span>Lotes en cuarentena</span><b>{data.quarantinedLots}</b></div></section>
 <div className="inventory-actions"><button onClick={()=>{setItem(emptyItem);setDialog('item')}}><Plus/>Nuevo artículo</button><button disabled={!data.items.some(i=>i.trackLots)} onClick={()=>{setLot({...lot,itemId:data.items.find(i=>i.trackLots)?.id??''});setDialog('lot')}}><ClipboardPlus/>Registrar lote</button><button disabled={!data.items.length||!plant.warehouses.length} onClick={()=>{setMove({...move,itemId:data.items[0]?.id??'',warehouseId:plant.warehouses[0]?.id??''});setDialog('movement')}}><Plus/>Registrar movimiento</button></div>
 {!plant.warehouses.length&&<div className="inventory-callout"><Warehouse/><div><b>Configura al menos una bodega en Mi Planta</b><span>Los artículos se pueden crear ahora; las entradas y salidas necesitan una bodega que admita su categoría.</span></div></div>}
 <section className="inventory-layout"><div className="inventory-panel"><div className="inventory-title"><h2>Existencias</h2><small>{data.balances.length} posiciones</small></div>{!data.balances.length?<div className="inventory-empty">Aún no hay existencias. Registra una entrada cuando tengas una bodega configurada.</div>:<div className="inventory-table"><div className="inventory-row head"><span>Artículo</span><span>Bodega / ubicación</span><span>Lote / calidad</span><span>Cantidad</span></div>{data.balances.map((b,i)=><div className="inventory-row" key={`${b.itemId}-${b.warehouseId}-${b.locationId}-${b.lotId}-${i}`}><span><b>{b.itemCode}</b><small>{b.itemName}</small></span><span><b>{b.warehouseCode}</b><small>{b.locationCode||'Sin ubicación'}</small></span><span><b>{b.lotCode||'Sin lote'}</b><small>{b.qualityStatus?quality[b.qualityStatus]:''}</small></span><span className={b.quantity<b.minimumStock?'stock-low':''}><b>{b.quantity.toLocaleString('es-CO')} {b.baseUnit}</b><small>Mín. {b.minimumStock}</small></span></div>)}</div>}</div>
 <div className="inventory-panel"><div className="inventory-title"><h2>Catálogo</h2><small>{data.items.length} artículos</small></div>{!data.items.length?<div className="inventory-empty">Crea materias primas, empaques, insumos, producto terminado o repuestos.</div>:<div className="catalog-list">{data.items.map(i=><article key={i.id}><span>{categories[i.category]??i.category}</span><b>{i.code} · {i.name}</b><small>{i.baseUnit} · {i.trackLots?'Control por lote':'Sin lotes'} · mínimo {i.minimumStock}</small></article>)}</div>}</div></section>
 {dialog&&<div className="inventory-modal" role="dialog" aria-modal="true"><form onSubmit={e=>{e.preventDefault();if(dialog==='item')void run(()=>createInventoryItem(plant.site.id,item),'Artículo creado');if(dialog==='lot')void run(()=>createInventoryLot(lot.itemId,{...lot,expiryDate:lot.expiryDate||null}),'Lote registrado');if(dialog==='movement')void run(()=>createInventoryMovement({...move,lotId:move.lotId||null,locationId:move.locationId||null}),'Movimiento registrado')}}><div className="inventory-title"><h2>{dialog==='item'?'Nuevo artículo':dialog==='lot'?'Registrar lote':'Registrar movimiento'}</h2><button type="button" onClick={()=>setDialog(null)}>×</button></div>
 {dialog==='item'&&<div className="inventory-form"><label>Código<input required value={item.code} onChange={e=>setItem({...item,code:e.target.value.toUpperCase()})}/></label><label>Nombre<input required value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></label><label>Categoría<select value={item.category} onChange={e=>setItem({...item,category:e.target.value})}>{Object.entries(categories).map(([v,l])=><option value={v}>{l}</option>)}</select></label><label>Unidad base<select value={item.baseUnit} onChange={e=>setItem({...item,baseUnit:e.target.value})}><option>KG</option><option>G</option><option>L</option><option>ML</option><option>UND</option></select></label><label>Existencia mínima<input type="number" min="0" step="0.001" value={item.minimumStock} onChange={e=>setItem({...item,minimumStock:+e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={item.trackLots} onChange={e=>setItem({...item,trackLots:e.target.checked})}/>Controlar por lote</label><label className="wide">Notas<textarea value={item.notes} onChange={e=>setItem({...item,notes:e.target.value})}/></label></div>}
 {dialog==='lot'&&<div className="inventory-form"><label>Artículo<select required value={lot.itemId} onChange={e=>setLot({...lot,itemId:e.target.value})}>{data.items.filter(i=>i.trackLots).map(i=><option value={i.id}>{i.code} · {i.name}</option>)}</select></label><label>Código interno<input required value={lot.internalCode} onChange={e=>setLot({...lot,internalCode:e.target.value.toUpperCase()})}/></label><label>Lote proveedor<input value={lot.supplierLot} onChange={e=>setLot({...lot,supplierLot:e.target.value})}/></label><label>Vencimiento<input type="date" value={lot.expiryDate} onChange={e=>setLot({...lot,expiryDate:e.target.value})}/></label><label>Calidad<select value={lot.qualityStatus} onChange={e=>setLot({...lot,qualityStatus:e.target.value})}>{Object.entries(quality).map(([v,l])=><option value={v}>{l}</option>)}</select></label></div>}
 {dialog==='movement'&&<div className="inventory-form"><label>Artículo<select required value={move.itemId} onChange={e=>setMove({...move,itemId:e.target.value,lotId:''})}>{data.items.map(i=><option value={i.id}>{i.code} · {i.name}</option>)}</select></label><label>Tipo<select value={move.movementType} onChange={e=>setMove({...move,movementType:e.target.value})}><option value="RECEIPT">Entrada</option><option value="ISSUE">Salida</option><option value="ADJUSTMENT_IN">Ajuste positivo</option><option value="ADJUSTMENT_OUT">Ajuste negativo</option><option value="CONSUMPTION">Consumo de producción</option><option value="DISPOSAL">Baja</option></select></label><label>Bodega<select required value={move.warehouseId} onChange={e=>setMove({...move,warehouseId:e.target.value,locationId:''})}>{plant.warehouses.filter(w=>!selectedItem||w.allowedCategories.includes(selectedItem.category)).map(w=><option value={w.id}>{w.code} · {w.name}</option>)}</select></label><label>Ubicación<select value={move.locationId} onChange={e=>setMove({...move,locationId:e.target.value})}><option value="">Sin ubicación</option>{selectedWarehouse?.locations.map(l=><option value={l.id}>{l.code} · {l.name}</option>)}</select></label>{selectedItem?.trackLots&&<label>Lote<select required value={move.lotId} onChange={e=>setMove({...move,lotId:e.target.value})}><option value="">Seleccionar…</option>{data.lots.filter(l=>l.itemId===move.itemId).map(l=><option value={l.id}>{l.internalCode} · {quality[l.qualityStatus]}</option>)}</select></label>}<label>Cantidad<input required type="number" min="0.001" step="0.001" value={move.quantity||''} onChange={e=>setMove({...move,quantity:+e.target.value})}/></label><label>Referencia<input value={move.reference} onChange={e=>setMove({...move,reference:e.target.value})} placeholder="OC, OP o documento"/></label><label className="wide">Notas<textarea value={move.notes} onChange={e=>setMove({...move,notes:e.target.value})}/></label></div>}
 <div className="inventory-submit"><button type="button" onClick={()=>setDialog(null)}>Cancelar</button><button disabled={busy}>{busy?'Guardando…':'Guardar'}</button></div></form></div>}</main>
}
