import { useState } from 'react'
import { Eye, EyeOff, ShieldCheck, UserPlus, X } from 'lucide-react'
import { registerUser } from './api'

export default function UserRegistration({onClose}:{onClose:()=>void}){
 const [form,setForm]=useState({displayName:'',username:'',role:'OPERATOR',password:'',confirm:''}),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSuccess('');if(form.password!==form.confirm){setError('Las contraseñas no coinciden');return}setBusy(true);try{const created=await registerUser({displayName:form.displayName,username:form.username,role:form.role,password:form.password});setSuccess(`${created.displayName} fue registrado como ${created.role}`);setForm({displayName:'',username:'',role:'OPERATOR',password:'',confirm:''})}catch(err){setError(err instanceof Error?err.message:'No fue posible registrar el usuario')}finally{setBusy(false)}}
 return <div className="user-modal" role="dialog" aria-modal="true" aria-labelledby="register-title"><form onSubmit={submit}><header><div className="user-modal-icon"><UserPlus/></div><div><span>ADMINISTRACIÓN DE ACCESO</span><h2 id="register-title">Registrar usuario</h2></div><button type="button" aria-label="Cerrar registro" onClick={onClose}><X/></button></header><p>La nueva cuenta podrá entrar a SDBrewPi Control según el rol asignado.</p><div className="user-form-grid"><label>Nombre completo<input required minLength={2} maxLength={160} value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>Correo o usuario<input required minLength={3} maxLength={160} autoComplete="off" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Rol<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="OPERATOR">Operador</option><option value="VIEWER">Solo lectura</option><option value="ADMIN">Administrador</option></select></label><div className="role-help"><ShieldCheck/><span>{form.role==='ADMIN'?'Configuración, usuarios y operación completa.':form.role==='OPERATOR'?'Operación de procesos sin administrar usuarios.':'Consulta de información sin cambios operativos.'}</span></div><label>Contraseña<div className="password-field"><input required minLength={8} maxLength={128} type={visible?'text':'password'} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" aria-label={visible?'Ocultar contraseña':'Mostrar contraseña'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff/>:<Eye/>}</button></div></label><label>Confirmar contraseña<input required minLength={8} maxLength={128} type={visible?'text':'password'} autoComplete="new-password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label></div>{error&&<div className="message error">{error}</div>}{success&&<div className="message success">{success}</div>}<footer><button type="button" onClick={onClose}>Cancelar</button><button disabled={busy}>{busy?'Registrando…':'Crear usuario'}</button></footer></form></div>
}
