CREATE TABLE fermentation_measurement (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tank_id VARCHAR(32) NOT NULL REFERENCES fermentation_tank(id),
  source VARCHAR(40) NOT NULL,
  captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  temperature_c NUMERIC(5,2),
  gravity NUMERIC(6,4),
  quality VARCHAR(32) NOT NULL
);

CREATE INDEX idx_fermentation_measurement_tank_time
  ON fermentation_measurement (tank_id, captured_at DESC);

CREATE TABLE fermentation_alarm (
  id VARCHAR(36) PRIMARY KEY,
  alarm_key VARCHAR(100) NOT NULL,
  target_id VARCHAR(64) NOT NULL,
  code VARCHAR(40) NOT NULL,
  severity VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  message VARCHAR(300) NOT NULL,
  source VARCHAR(40) NOT NULL,
  opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
  last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
  cleared_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_fermentation_alarm_status_time
  ON fermentation_alarm (status, opened_at DESC);
